spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/gdc
spring.datasource.username=gdc_user
spring.datasource.password=Hello@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true