CREATE SEQUENCE IF NOT EXISTS patient_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    gender VARCHAR(10) NOT NULL,
    age SMALLINT NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    referred_by VARCHAR(20),
    doctor_name VARCHAR(100),
    consultation_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    registration_date TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_patients_age
        CHECK (age BETWEEN 1 AND 120),
    CONSTRAINT chk_patients_gender
        CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_patients_referred_by
        CHECK (
            referred_by IS NULL
            OR referred_by IN ('DOCTOR', 'PATIENT', 'ONLINE', 'SELF', 'OTHER')
        ),
    CONSTRAINT chk_patients_consultation_fee
        CHECK (consultation_fee >= 0),
    CONSTRAINT chk_patients_doctor_referral
        CHECK (
            referred_by <> 'DOCTOR'
            OR doctor_name IS NOT NULL
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_patients_first_name_mobile
    ON patients (LOWER(TRIM(first_name)), mobile);

CREATE INDEX IF NOT EXISTS idx_patients_mobile
    ON patients (mobile);

CREATE INDEX IF NOT EXISTS idx_patients_active
    ON patients (is_active);
