CREATE SEQUENCE patient_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    patient_id VARCHAR(20) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    gender VARCHAR(10) NOT NULL,
    age SMALLINT NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    referred_by VARCHAR(20) NOT NULL,
    doctor_name VARCHAR(100),
    consultation_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    registration_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_patients PRIMARY KEY (id),
    CONSTRAINT uk_patients_patient_id UNIQUE (patient_id),
    CONSTRAINT chk_patients_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_patients_age CHECK (age BETWEEN 1 AND 120),
    CONSTRAINT chk_patients_mobile CHECK (mobile ~ '^[0-9]{10}$'),
    CONSTRAINT chk_patients_referred_by CHECK (referred_by IN ('DOCTOR', 'PATIENT', 'ONLINE', 'SELF', 'OTHER')),
    CONSTRAINT chk_patients_doctor_referral CHECK (
        referred_by <> 'DOCTOR'
        OR NULLIF(BTRIM(doctor_name), '') IS NOT NULL
    ),
    CONSTRAINT chk_patients_consultation_fee CHECK (consultation_fee >= 0.00)
);

CREATE UNIQUE INDEX uk_patients_first_name_mobile
    ON patients (LOWER(BTRIM(first_name)), mobile);

CREATE INDEX idx_patients_active
    ON patients (is_active);

CREATE INDEX idx_patients_mobile
    ON patients (mobile);

CREATE INDEX idx_patients_active_name
    ON patients (is_active, first_name, last_name, patient_id);
