CREATE SEQUENCE appointment_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE appointment_slot_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slot_start TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reservation_type VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    released_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_appointment_slot_reservations PRIMARY KEY (id),
    CONSTRAINT chk_appointment_slot_reservations_type CHECK (reservation_type IN ('APPOINTMENT', 'DOCTOR_BUSY'))
);

CREATE UNIQUE INDEX uk_appointment_slot_reservations_active_slot_start
    ON appointment_slot_reservations (slot_start)
    WHERE is_active = TRUE;

CREATE INDEX idx_appointment_slot_reservations_active_range
    ON appointment_slot_reservations (is_active, slot_start);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    appointment_id VARCHAR(20) NOT NULL,
    slot_reservation_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    appointment_datetime TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    appointment_type VARCHAR(20) NOT NULL,
    notes VARCHAR(1000),
    systolic_bp SMALLINT,
    diastolic_bp SMALLINT,
    heart_rate SMALLINT,
    breathing_rate SMALLINT,
    height_cm NUMERIC(5, 2),
    weight_kg NUMERIC(5, 2),
    bmi NUMERIC(5, 2),
    fbs NUMERIC(6, 2),
    rbs NUMERIC(6, 2),
    has_diabetes BOOLEAN NOT NULL DEFAULT FALSE,
    has_hypertension BOOLEAN NOT NULL DEFAULT FALSE,
    has_heart_disease BOOLEAN NOT NULL DEFAULT FALSE,
    has_asthma BOOLEAN NOT NULL DEFAULT FALSE,
    has_kidney_disease BOOLEAN NOT NULL DEFAULT FALSE,
    has_liver_disease BOOLEAN NOT NULL DEFAULT FALSE,
    has_thyroid_disorder BOOLEAN NOT NULL DEFAULT FALSE,
    has_bleeding_disorders BOOLEAN NOT NULL DEFAULT FALSE,
    has_neurological_issues BOOLEAN NOT NULL DEFAULT FALSE,
    has_drug_allergy BOOLEAN NOT NULL DEFAULT FALSE,
    has_food_allergy BOOLEAN NOT NULL DEFAULT FALSE,
    has_latex_allergy BOOLEAN NOT NULL DEFAULT FALSE,
    other_allergy_notes VARCHAR(500),
    past_surgical_history VARCHAR(1000),
    has_root_canal BOOLEAN NOT NULL DEFAULT FALSE,
    has_implants BOOLEAN NOT NULL DEFAULT FALSE,
    has_crowns_or_bridges BOOLEAN NOT NULL DEFAULT FALSE,
    has_braces BOOLEAN NOT NULL DEFAULT FALSE,
    has_dentures BOOLEAN NOT NULL DEFAULT FALSE,
    dental_complication_notes VARCHAR(1000),
    consent_given BOOLEAN NOT NULL DEFAULT FALSE,
    consent_reference VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT uk_appointments_appointment_id UNIQUE (appointment_id),
    CONSTRAINT uk_appointments_slot_reservation_id UNIQUE (slot_reservation_id),
    CONSTRAINT fk_appointments_slot_reservation FOREIGN KEY (slot_reservation_id)
        REFERENCES appointment_slot_reservations (id),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id)
        REFERENCES patients (id),
    CONSTRAINT chk_appointments_type CHECK (appointment_type IN ('NEW', 'FOLLOW_UP')),
    CONSTRAINT chk_appointments_systolic_bp CHECK (systolic_bp IS NULL OR systolic_bp BETWEEN 50 AND 260),
    CONSTRAINT chk_appointments_diastolic_bp CHECK (diastolic_bp IS NULL OR diastolic_bp BETWEEN 30 AND 180),
    CONSTRAINT chk_appointments_heart_rate CHECK (heart_rate IS NULL OR heart_rate BETWEEN 30 AND 220),
    CONSTRAINT chk_appointments_breathing_rate CHECK (breathing_rate IS NULL OR breathing_rate BETWEEN 5 AND 80),
    CONSTRAINT chk_appointments_height_cm CHECK (height_cm IS NULL OR height_cm BETWEEN 30.00 AND 250.00),
    CONSTRAINT chk_appointments_weight_kg CHECK (weight_kg IS NULL OR weight_kg BETWEEN 1.00 AND 350.00),
    CONSTRAINT chk_appointments_bmi CHECK (bmi IS NULL OR bmi BETWEEN 0.00 AND 999.99),
    CONSTRAINT chk_appointments_fbs CHECK (fbs IS NULL OR fbs BETWEEN 0.00 AND 1000.00),
    CONSTRAINT chk_appointments_rbs CHECK (rbs IS NULL OR rbs BETWEEN 0.00 AND 1000.00)
);

CREATE INDEX idx_appointments_patient
    ON appointments (patient_id);

CREATE INDEX idx_appointments_active_datetime
    ON appointments (is_active, appointment_datetime);

CREATE TABLE doctor_busy_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slot_reservation_id BIGINT NOT NULL,
    busy_datetime TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    notes VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_doctor_busy_slots PRIMARY KEY (id),
    CONSTRAINT uk_doctor_busy_slots_slot_reservation_id UNIQUE (slot_reservation_id),
    CONSTRAINT fk_doctor_busy_slots_slot_reservation FOREIGN KEY (slot_reservation_id)
        REFERENCES appointment_slot_reservations (id)
);

CREATE INDEX idx_doctor_busy_slots_active_datetime
    ON doctor_busy_slots (is_active, busy_datetime);
