CREATE SEQUENCE IF NOT EXISTS appointment_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE appointment_slot_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_start TIMESTAMPTZ NOT NULL,
    reservation_type VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    released_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_appointment_slot_reservation_type
        CHECK (reservation_type IN ('APPOINTMENT', 'DOCTOR_BUSY'))
);

-- This is the scheduling invariant:
-- a live clinic time slot can belong to only one appointment or doctor-busy entry.
CREATE UNIQUE INDEX uq_active_appointment_slot_reservations_slot_start
    ON appointment_slot_reservations (slot_start)
    WHERE is_active = TRUE;

CREATE INDEX idx_appointment_slot_reservations_range
    ON appointment_slot_reservations (slot_start, is_active);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id VARCHAR(20) NOT NULL UNIQUE,
    slot_reservation_id BIGINT NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL,
    appointment_datetime TIMESTAMPTZ NOT NULL,
    appointment_type VARCHAR(20) NOT NULL,
    notes VARCHAR(1000),

    systolic_bp SMALLINT,
    diastolic_bp SMALLINT,
    heart_rate SMALLINT,
    breathing_rate SMALLINT,
    height_cm NUMERIC(5,2),
    weight_kg NUMERIC(5,2),
    bmi NUMERIC(5,2),
    fbs NUMERIC(6,2),
    rbs NUMERIC(6,2),

    has_diabetes BOOLEAN NOT NULL DEFAULT FALSE,
    has_hypertension BOOLEAN NOT NULL DEFAULT FALSE,
    has_heart_disease BOOLEAN NOT NULL DEFAULT FALSE,
    has_asthma BOOLEAN NOT NULL DEFAULT FALSE,
    has_kidney_disease BOOLEAN NOT NULL DEFAULT FALSE,
    has_liver_disease BOOLEAN NOT NULL DEFAULT FALSE,
    has_thyroid_disorder BOOLEAN NOT NULL DEFAULT FALSE,
    has_bleeding_disorders BOOLEAN NOT NULL DEFAULT FALSE,
    has_neurological_issues BOOLEAN NOT NULL DEFAULT FALSE,

    has_drug_allergy BOOLEAN NOT NULL DEFAULT FALSE,
    has_food_allergy BOOLEAN NOT NULL DEFAULT FALSE,
    has_latex_allergy BOOLEAN NOT NULL DEFAULT FALSE,
    other_allergy_notes VARCHAR(500),

    past_surgical_history VARCHAR(1000),

    has_root_canal BOOLEAN NOT NULL DEFAULT FALSE,
    has_implants BOOLEAN NOT NULL DEFAULT FALSE,
    has_crowns_or_bridges BOOLEAN NOT NULL DEFAULT FALSE,
    has_braces BOOLEAN NOT NULL DEFAULT FALSE,
    has_dentures BOOLEAN NOT NULL DEFAULT FALSE,
    dental_complication_notes VARCHAR(1000),

    consent_given BOOLEAN NOT NULL DEFAULT FALSE,
    consent_reference VARCHAR(255),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_appointments_slot_reservation
        FOREIGN KEY (slot_reservation_id) REFERENCES appointment_slot_reservations (id),
    CONSTRAINT chk_appointments_type
        CHECK (appointment_type IN ('NEW', 'FOLLOW_UP')),
    CONSTRAINT chk_appointments_bp
        CHECK (
            (systolic_bp IS NULL OR systolic_bp BETWEEN 50 AND 260)
            AND (diastolic_bp IS NULL OR diastolic_bp BETWEEN 30 AND 180)
        ),
    CONSTRAINT chk_appointments_rates
        CHECK (
            (heart_rate IS NULL OR heart_rate BETWEEN 30 AND 220)
            AND (breathing_rate IS NULL OR breathing_rate BETWEEN 5 AND 80)
        ),
    CONSTRAINT chk_appointments_body_measurements
        CHECK (
            (height_cm IS NULL OR height_cm BETWEEN 30 AND 250)
            AND (weight_kg IS NULL OR weight_kg BETWEEN 1 AND 350)
            AND (bmi IS NULL OR bmi BETWEEN 1 AND 150)
        ),
    CONSTRAINT chk_appointments_glucose
        CHECK (
            (fbs IS NULL OR fbs BETWEEN 0 AND 1000)
            AND (rbs IS NULL OR rbs BETWEEN 0 AND 1000)
        )
);

CREATE INDEX idx_appointments_datetime_active
    ON appointments (appointment_datetime, is_active);

CREATE INDEX idx_appointments_patient
    ON appointments (patient_id);

CREATE TABLE doctor_busy_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_reservation_id BIGINT NOT NULL UNIQUE,
    busy_datetime TIMESTAMPTZ NOT NULL,
    notes VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_doctor_busy_slot_reservation
        FOREIGN KEY (slot_reservation_id) REFERENCES appointment_slot_reservations (id)
);

CREATE INDEX idx_doctor_busy_datetime_active
    ON doctor_busy_slots (busy_datetime, is_active);
