CREATE SEQUENCE IF NOT EXISTS treatment_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS follow_up_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id VARCHAR(30) NOT NULL UNIQUE,
    medicine_name VARCHAR(150) NOT NULL,
    available_quantity INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_medicines_available_quantity
        CHECK (available_quantity >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_medicines_name
    ON medicines (LOWER(TRIM(medicine_name)));

INSERT INTO medicines (medicine_id, medicine_name, available_quantity)
VALUES
    ('M-00001', 'Chymoral forte', 216),
    ('M-00002', 'Rodal mr', 289),
    ('M-00003', 'Pan d', 82)
ON CONFLICT (medicine_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS treatments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id VARCHAR(30) NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL,
    treatment_date TIMESTAMPTZ NOT NULL,
    treatment_type VARCHAR(20) NOT NULL,
    treatment_amount NUMERIC(10,2) NOT NULL,
    doctor_notes VARCHAR(2000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_treatments_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT chk_treatments_type
        CHECK (treatment_type IN ('ADVISED', 'DESIRED')),
    CONSTRAINT chk_treatments_amount
        CHECK (treatment_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_treatments_patient_date
    ON treatments (patient_id, treatment_date DESC);

CREATE TABLE IF NOT EXISTS follow_ups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follow_up_id VARCHAR(30) NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL,
    related_treatment_id BIGINT,
    follow_up_date TIMESTAMPTZ NOT NULL,
    doctor_notes VARCHAR(2000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_follow_ups_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_follow_ups_related_treatment
        FOREIGN KEY (related_treatment_id) REFERENCES treatments (id)
);

CREATE INDEX IF NOT EXISTS idx_follow_ups_patient_date
    ON follow_ups (patient_id, follow_up_date DESC);

CREATE TABLE IF NOT EXISTS clinical_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id BIGINT,
    follow_up_id BIGINT,
    problem_type VARCHAR(40) NOT NULL,
    notes VARCHAR(2000),
    impaction_type VARCHAR(40),
    CONSTRAINT fk_clinical_problems_treatment
        FOREIGN KEY (treatment_id) REFERENCES treatments (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_clinical_problems_follow_up
        FOREIGN KEY (follow_up_id) REFERENCES follow_ups (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_clinical_problems_owner
        CHECK (
            (treatment_id IS NOT NULL AND follow_up_id IS NULL)
            OR (treatment_id IS NULL AND follow_up_id IS NOT NULL)
        ),
    CONSTRAINT chk_clinical_problems_type
        CHECK (
            problem_type IN (
                'ROOT_CANAL',
                'IMPLANTS',
                'IMPACTION',
                'CROWNS_BRIDGES',
                'BRACES',
                'DENTURES',
                'EXTRACTION',
                'FILLING',
                'SCALING',
                'CERVICAL_ABRASION',
                'GENERALIZED_GINGIVITIS'
            )
        ),
    CONSTRAINT chk_clinical_problems_impaction
        CHECK (
            impaction_type IS NULL
            OR impaction_type IN ('MESIO_ANGULAR', 'DISTO_ANGULAR', 'VERTICAL', 'HORIZONTAL')
        )
);

CREATE INDEX IF NOT EXISTS idx_clinical_problems_treatment
    ON clinical_problems (treatment_id);

CREATE INDEX IF NOT EXISTS idx_clinical_problems_follow_up
    ON clinical_problems (follow_up_id);

CREATE TABLE IF NOT EXISTS clinical_problem_teeth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    tooth_number INTEGER NOT NULL,
    CONSTRAINT fk_clinical_problem_teeth_problem
        FOREIGN KEY (problem_id) REFERENCES clinical_problems (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_clinical_problem_teeth_fdi
        CHECK (
            tooth_number IN (
                18,17,16,15,14,13,12,11,
                21,22,23,24,25,26,27,28,
                48,47,46,45,44,43,42,41,
                31,32,33,34,35,36,37,38
            )
        ),
    CONSTRAINT uq_clinical_problem_teeth
        UNIQUE (problem_id, tooth_number)
);

CREATE TABLE IF NOT EXISTS root_canal_lengths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    tooth_number INTEGER NOT NULL,
    canal_name VARCHAR(40) NOT NULL,
    length_mm NUMERIC(5,2),
    notes VARCHAR(500),
    CONSTRAINT fk_root_canal_lengths_problem
        FOREIGN KEY (problem_id) REFERENCES clinical_problems (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_root_canal_lengths_value
        CHECK (length_mm IS NULL OR length_mm > 0),
    CONSTRAINT uq_root_canal_lengths
        UNIQUE (problem_id, tooth_number, canal_name)
);

CREATE TABLE IF NOT EXISTS implant_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL UNIQUE,
    implant_type VARCHAR(30),
    implant_width_mm NUMERIC(5,2),
    implant_length_mm NUMERIC(5,2),
    implant_company VARCHAR(150),
    healing_cap_placement_date DATE,
    abutment_placement_date DATE,
    crown_placement_date DATE,
    CONSTRAINT fk_implant_details_problem
        FOREIGN KEY (problem_id) REFERENCES clinical_problems (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_implant_details_type
        CHECK (implant_type IS NULL OR implant_type IN ('BASAL', 'CONVENTIONAL')),
    CONSTRAINT chk_implant_details_width
        CHECK (implant_width_mm IS NULL OR implant_width_mm > 0),
    CONSTRAINT chk_implant_details_length
        CHECK (implant_length_mm IS NULL OR implant_length_mm > 0)
);

CREATE TABLE IF NOT EXISTS prescription_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id BIGINT,
    follow_up_id BIGINT,
    medicine_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_prescription_items_treatment
        FOREIGN KEY (treatment_id) REFERENCES treatments (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prescription_items_follow_up
        FOREIGN KEY (follow_up_id) REFERENCES follow_ups (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_prescription_items_medicine
        FOREIGN KEY (medicine_id) REFERENCES medicines (id),
    CONSTRAINT chk_prescription_items_owner
        CHECK (
            (treatment_id IS NOT NULL AND follow_up_id IS NULL)
            OR (treatment_id IS NULL AND follow_up_id IS NOT NULL)
        ),
    CONSTRAINT chk_prescription_items_quantity
        CHECK (quantity > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_prescription_items_treatment_medicine
    ON prescription_items (treatment_id, medicine_id)
    WHERE treatment_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_prescription_items_follow_up_medicine
    ON prescription_items (follow_up_id, medicine_id)
    WHERE follow_up_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS clinical_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id BIGINT,
    follow_up_id BIGINT,
    stored_filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_clinical_scans_treatment
        FOREIGN KEY (treatment_id) REFERENCES treatments (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_clinical_scans_follow_up
        FOREIGN KEY (follow_up_id) REFERENCES follow_ups (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_clinical_scans_owner
        CHECK (
            (treatment_id IS NOT NULL AND follow_up_id IS NULL)
            OR (treatment_id IS NULL AND follow_up_id IS NOT NULL)
        ),
    CONSTRAINT chk_clinical_scans_size
        CHECK (file_size_bytes > 0)
);

CREATE INDEX IF NOT EXISTS idx_clinical_scans_treatment
    ON clinical_scans (treatment_id);

CREATE INDEX IF NOT EXISTS idx_clinical_scans_follow_up
    ON clinical_scans (follow_up_id);
