CREATE SEQUENCE IF NOT EXISTS medicine_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS pharmacy_payment_number_seq
    START WITH 1
    INCREMENT BY 1;

ALTER TABLE medicines
    ADD COLUMN IF NOT EXISTS expiry_date DATE;

UPDATE medicines
SET expiry_date = CURRENT_DATE + INTERVAL '1 year'
WHERE expiry_date IS NULL;

ALTER TABLE medicines
    ALTER COLUMN expiry_date SET NOT NULL;

SELECT setval(
    'medicine_number_seq',
    GREATEST(
        COALESCE(
            (
                SELECT MAX(SUBSTRING(medicine_id FROM 3)::INTEGER) + 1
                FROM medicines
                WHERE medicine_id ~ '^M-[0-9]{5}$'
            ),
            1
        ),
        1
    ),
    false
);

CREATE TABLE IF NOT EXISTS pharmacy_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(30) NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL,
    payment_mode VARCHAR(20) NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    details VARCHAR(1000),
    paid_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_pharmacy_payments_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT chk_pharmacy_payments_mode
        CHECK (payment_mode IN ('CASH', 'UPI')),
    CONSTRAINT chk_pharmacy_payments_total
        CHECK (total_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_pharmacy_payments_patient_paid_at
    ON pharmacy_payments (patient_id, paid_at DESC);

CREATE TABLE IF NOT EXISTS pharmacy_payment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    prescription_item_id BIGINT NOT NULL UNIQUE,
    medicine_id BIGINT NOT NULL,
    prescribed_quantity INTEGER NOT NULL,
    dispensed_quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    line_total NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_pharmacy_payment_items_payment
        FOREIGN KEY (payment_id) REFERENCES pharmacy_payments (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pharmacy_payment_items_prescription
        FOREIGN KEY (prescription_item_id) REFERENCES prescription_items (id),
    CONSTRAINT fk_pharmacy_payment_items_medicine
        FOREIGN KEY (medicine_id) REFERENCES medicines (id),
    CONSTRAINT chk_pharmacy_payment_items_prescribed_quantity
        CHECK (prescribed_quantity > 0),
    CONSTRAINT chk_pharmacy_payment_items_dispensed_quantity
        CHECK (dispensed_quantity > 0),
    CONSTRAINT chk_pharmacy_payment_items_unit_price
        CHECK (unit_price >= 0),
    CONSTRAINT chk_pharmacy_payment_items_line_total
        CHECK (line_total >= 0),
    CONSTRAINT chk_pharmacy_payment_items_full_fulfilment
        CHECK (dispensed_quantity = prescribed_quantity)
);

CREATE INDEX IF NOT EXISTS idx_pharmacy_payment_items_payment
    ON pharmacy_payment_items (payment_id);

CREATE INDEX IF NOT EXISTS idx_pharmacy_payment_items_medicine
    ON pharmacy_payment_items (medicine_id);

CREATE TABLE IF NOT EXISTS medicine_stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id BIGINT NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    quantity_delta INTEGER NOT NULL,
    reference_type VARCHAR(40),
    reference_id VARCHAR(30),
    notes VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_medicine_stock_movements_medicine
        FOREIGN KEY (medicine_id) REFERENCES medicines (id),
    CONSTRAINT chk_medicine_stock_movements_type
        CHECK (movement_type IN ('STOCK_ADD', 'STOCK_ADJUSTMENT', 'DISPENSE')),
    CONSTRAINT chk_medicine_stock_movements_delta
        CHECK (quantity_delta <> 0)
);

CREATE INDEX IF NOT EXISTS idx_medicine_stock_movements_medicine_created
    ON medicine_stock_movements (medicine_id, created_at DESC);
