CREATE SEQUENCE IF NOT EXISTS treatment_payment_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(30) NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL,
    treatment_id BIGINT NOT NULL UNIQUE,
    payment_mode VARCHAR(20) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    details VARCHAR(1000),
    paid_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_payments_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_payments_treatment
        FOREIGN KEY (treatment_id) REFERENCES treatments (id),
    CONSTRAINT chk_payments_mode
        CHECK (payment_mode IN ('CASH', 'UPI')),
    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0)
);

SELECT setval(
    'treatment_payment_number_seq',
    GREATEST(
        COALESCE(
            (
                SELECT MAX(SUBSTRING(payment_id FROM 6)::INTEGER) + 1
                FROM payments
                WHERE payment_id ~ '^TPAY-[0-9]{5}$'
            ),
            1
        ),
        1
    ),
    false
);

CREATE INDEX IF NOT EXISTS idx_payments_patient_paid_at
    ON payments (patient_id, paid_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_payments_treatment
    ON payments (treatment_id);
