CREATE SEQUENCE IF NOT EXISTS treatment_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS follow_up_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS medicine_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS pharmacy_payment_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS treatment_payment_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE medicines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    medicine_id VARCHAR(30) NOT NULL,
    medicine_name VARCHAR(150) NOT NULL,
    available_quantity INTEGER NOT NULL DEFAULT 0,
    expiry_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_medicines PRIMARY KEY (id),
    CONSTRAINT uk_medicines_medicine_id UNIQUE (medicine_id),
    CONSTRAINT chk_medicines_available_quantity CHECK (available_quantity >= 0)
);

CREATE UNIQUE INDEX uk_medicines_active_normalized_name
    ON medicines (LOWER(BTRIM(medicine_name)))
    WHERE is_active = TRUE;

CREATE INDEX idx_medicines_active_expiry_name
    ON medicines (is_active, expiry_date, medicine_name);

CREATE TABLE treatments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    treatment_id VARCHAR(30) NOT NULL,
    patient_id BIGINT NOT NULL,
    treatment_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    treatment_type VARCHAR(20) NOT NULL,
    treatment_amount NUMERIC(10, 2) NOT NULL,
    doctor_notes VARCHAR(2000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_treatments PRIMARY KEY (id),
    CONSTRAINT uk_treatments_treatment_id UNIQUE (treatment_id),
    CONSTRAINT fk_treatments_patient FOREIGN KEY (patient_id)
        REFERENCES patients (id),
    CONSTRAINT chk_treatments_type CHECK (treatment_type IN ('ADVISED', 'DESIRED')),
    CONSTRAINT chk_treatments_amount CHECK (treatment_amount >= 0.00)
);

CREATE INDEX idx_treatments_patient_active_date
    ON treatments (patient_id, is_active, treatment_date DESC, id DESC);

CREATE TABLE follow_ups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    follow_up_id VARCHAR(30) NOT NULL,
    patient_id BIGINT NOT NULL,
    related_treatment_id BIGINT,
    follow_up_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    doctor_notes VARCHAR(2000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_follow_ups PRIMARY KEY (id),
    CONSTRAINT uk_follow_ups_follow_up_id UNIQUE (follow_up_id),
    CONSTRAINT fk_follow_ups_patient FOREIGN KEY (patient_id)
        REFERENCES patients (id),
    CONSTRAINT fk_follow_ups_related_treatment FOREIGN KEY (related_treatment_id)
        REFERENCES treatments (id)
);

CREATE INDEX idx_follow_ups_patient_active_date
    ON follow_ups (patient_id, is_active, follow_up_date DESC, id DESC);

CREATE TABLE clinical_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    treatment_id BIGINT,
    follow_up_id BIGINT,
    problem_type VARCHAR(40) NOT NULL,
    notes VARCHAR(2000),
    impaction_type VARCHAR(40),

    CONSTRAINT pk_clinical_problems PRIMARY KEY (id),
    CONSTRAINT fk_clinical_problems_treatment FOREIGN KEY (treatment_id)
        REFERENCES treatments (id),
    CONSTRAINT fk_clinical_problems_follow_up FOREIGN KEY (follow_up_id)
        REFERENCES follow_ups (id),
    CONSTRAINT chk_clinical_problems_owner CHECK (
        (treatment_id IS NOT NULL AND follow_up_id IS NULL)
        OR (treatment_id IS NULL AND follow_up_id IS NOT NULL)
    ),
    CONSTRAINT chk_clinical_problems_type CHECK (
        problem_type IN (
            'ROOT_CANAL',
            'IMPLANTS',
            'IMPACTION',
            'CROWNS_BRIDGES',
            'BRACES',
            'DENTURES',
            'EXTRACTION',
            'FILLING',
            'SCALING',
            'CERVICAL_ABRASION',
            'GENERALIZED_GINGIVITIS'
        )
    ),
    CONSTRAINT chk_clinical_problems_impaction_type CHECK (
        impaction_type IS NULL
        OR impaction_type IN ('MESIO_ANGULAR', 'DISTO_ANGULAR', 'VERTICAL', 'HORIZONTAL')
    )
);

CREATE INDEX idx_clinical_problems_treatment
    ON clinical_problems (treatment_id);

CREATE INDEX idx_clinical_problems_follow_up
    ON clinical_problems (follow_up_id);

CREATE TABLE clinical_problem_teeth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id BIGINT NOT NULL,
    tooth_number INTEGER NOT NULL,

    CONSTRAINT pk_clinical_problem_teeth PRIMARY KEY (id),
    CONSTRAINT fk_clinical_problem_teeth_problem FOREIGN KEY (problem_id)
        REFERENCES clinical_problems (id),
    CONSTRAINT chk_clinical_problem_teeth_number CHECK (tooth_number BETWEEN 11 AND 48)
);

CREATE INDEX idx_clinical_problem_teeth_problem
    ON clinical_problem_teeth (problem_id);

CREATE TABLE root_canal_lengths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id BIGINT NOT NULL,
    tooth_number INTEGER NOT NULL,
    canal_name VARCHAR(40) NOT NULL,
    length_mm NUMERIC(5, 2),
    notes VARCHAR(500),

    CONSTRAINT pk_root_canal_lengths PRIMARY KEY (id),
    CONSTRAINT fk_root_canal_lengths_problem FOREIGN KEY (problem_id)
        REFERENCES clinical_problems (id),
    CONSTRAINT chk_root_canal_lengths_tooth_number CHECK (tooth_number BETWEEN 11 AND 48),
    CONSTRAINT chk_root_canal_lengths_length CHECK (length_mm IS NULL OR length_mm > 0.00)
);

CREATE INDEX idx_root_canal_lengths_problem
    ON root_canal_lengths (problem_id);

CREATE TABLE implant_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    problem_id BIGINT NOT NULL,
    implant_type VARCHAR(30),
    implant_width_mm NUMERIC(5, 2),
    implant_length_mm NUMERIC(5, 2),
    implant_company VARCHAR(150),
    healing_cap_placement_date DATE,
    abutment_placement_date DATE,
    crown_placement_date DATE,

    CONSTRAINT pk_implant_details PRIMARY KEY (id),
    CONSTRAINT uk_implant_details_problem_id UNIQUE (problem_id),
    CONSTRAINT fk_implant_details_problem FOREIGN KEY (problem_id)
        REFERENCES clinical_problems (id),
    CONSTRAINT chk_implant_details_type CHECK (
        implant_type IS NULL
        OR implant_type IN ('BASAL', 'CONVENTIONAL')
    ),
    CONSTRAINT chk_implant_details_width CHECK (implant_width_mm IS NULL OR implant_width_mm > 0.00),
    CONSTRAINT chk_implant_details_length CHECK (implant_length_mm IS NULL OR implant_length_mm > 0.00)
);

CREATE TABLE prescription_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    treatment_id BIGINT,
    follow_up_id BIGINT,
    medicine_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,

    CONSTRAINT pk_prescription_items PRIMARY KEY (id),
    CONSTRAINT fk_prescription_items_treatment FOREIGN KEY (treatment_id)
        REFERENCES treatments (id),
    CONSTRAINT fk_prescription_items_follow_up FOREIGN KEY (follow_up_id)
        REFERENCES follow_ups (id),
    CONSTRAINT fk_prescription_items_medicine FOREIGN KEY (medicine_id)
        REFERENCES medicines (id),
    CONSTRAINT chk_prescription_items_owner CHECK (
        (treatment_id IS NOT NULL AND follow_up_id IS NULL)
        OR (treatment_id IS NULL AND follow_up_id IS NOT NULL)
    ),
    CONSTRAINT chk_prescription_items_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_prescription_items_treatment
    ON prescription_items (treatment_id);

CREATE INDEX idx_prescription_items_follow_up
    ON prescription_items (follow_up_id);

CREATE INDEX idx_prescription_items_medicine
    ON prescription_items (medicine_id);

CREATE TABLE clinical_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    treatment_id BIGINT,
    follow_up_id BIGINT,
    stored_filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_clinical_scans PRIMARY KEY (id),
    CONSTRAINT fk_clinical_scans_treatment FOREIGN KEY (treatment_id)
        REFERENCES treatments (id),
    CONSTRAINT fk_clinical_scans_follow_up FOREIGN KEY (follow_up_id)
        REFERENCES follow_ups (id),
    CONSTRAINT chk_clinical_scans_owner CHECK (
        (treatment_id IS NOT NULL AND follow_up_id IS NULL)
        OR (treatment_id IS NULL AND follow_up_id IS NOT NULL)
    ),
    CONSTRAINT chk_clinical_scans_file_size CHECK (file_size_bytes >= 0)
);

CREATE INDEX idx_clinical_scans_treatment
    ON clinical_scans (treatment_id);

CREATE INDEX idx_clinical_scans_follow_up
    ON clinical_scans (follow_up_id);

CREATE TABLE medicine_stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    medicine_id BIGINT NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    quantity_delta INTEGER NOT NULL,
    reference_type VARCHAR(40),
    reference_id VARCHAR(30),
    notes VARCHAR(500),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_medicine_stock_movements PRIMARY KEY (id),
    CONSTRAINT fk_medicine_stock_movements_medicine FOREIGN KEY (medicine_id)
        REFERENCES medicines (id),
    CONSTRAINT chk_medicine_stock_movements_type CHECK (
        movement_type IN ('STOCK_ADD', 'STOCK_ADJUSTMENT', 'DISPENSE')
    )
);

CREATE INDEX idx_medicine_stock_movements_medicine
    ON medicine_stock_movements (medicine_id);

CREATE TABLE pharmacy_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payment_id VARCHAR(30) NOT NULL,
    patient_id BIGINT NOT NULL,
    payment_mode VARCHAR(20) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    details VARCHAR(1000),
    paid_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_pharmacy_payments PRIMARY KEY (id),
    CONSTRAINT uk_pharmacy_payments_payment_id UNIQUE (payment_id),
    CONSTRAINT fk_pharmacy_payments_patient FOREIGN KEY (patient_id)
        REFERENCES patients (id),
    CONSTRAINT chk_pharmacy_payments_mode CHECK (payment_mode IN ('CASH', 'UPI')),
    CONSTRAINT chk_pharmacy_payments_total_amount CHECK (total_amount >= 0.00)
);

CREATE INDEX idx_pharmacy_payments_patient_paid_at
    ON pharmacy_payments (patient_id, paid_at DESC, id DESC);

CREATE TABLE pharmacy_payment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payment_id BIGINT NOT NULL,
    prescription_item_id BIGINT NOT NULL,
    medicine_id BIGINT NOT NULL,
    prescribed_quantity INTEGER NOT NULL,
    dispensed_quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    line_total NUMERIC(10, 2) NOT NULL,

    CONSTRAINT pk_pharmacy_payment_items PRIMARY KEY (id),
    CONSTRAINT fk_pharmacy_payment_items_payment FOREIGN KEY (payment_id)
        REFERENCES pharmacy_payments (id),
    CONSTRAINT fk_pharmacy_payment_items_prescription_item FOREIGN KEY (prescription_item_id)
        REFERENCES prescription_items (id),
    CONSTRAINT fk_pharmacy_payment_items_medicine FOREIGN KEY (medicine_id)
        REFERENCES medicines (id),
    CONSTRAINT uk_pharmacy_payment_items_prescription_item_id UNIQUE (prescription_item_id),
    CONSTRAINT chk_pharmacy_payment_items_prescribed_quantity CHECK (prescribed_quantity > 0),
    CONSTRAINT chk_pharmacy_payment_items_dispensed_quantity CHECK (dispensed_quantity >= 0),
    CONSTRAINT chk_pharmacy_payment_items_unit_price CHECK (unit_price >= 0.00),
    CONSTRAINT chk_pharmacy_payment_items_line_total CHECK (line_total >= 0.00)
);

CREATE INDEX idx_pharmacy_payment_items_payment
    ON pharmacy_payment_items (payment_id);

CREATE INDEX idx_pharmacy_payment_items_medicine
    ON pharmacy_payment_items (medicine_id);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payment_id VARCHAR(30) NOT NULL,
    patient_id BIGINT NOT NULL,
    treatment_id BIGINT NOT NULL,
    payment_mode VARCHAR(20) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    details VARCHAR(1000),
    paid_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT uk_payments_payment_id UNIQUE (payment_id),
    CONSTRAINT uk_payments_treatment_id UNIQUE (treatment_id),
    CONSTRAINT fk_payments_patient FOREIGN KEY (patient_id)
        REFERENCES patients (id),
    CONSTRAINT fk_payments_treatment FOREIGN KEY (treatment_id)
        REFERENCES treatments (id),
    CONSTRAINT chk_payments_mode CHECK (payment_mode IN ('CASH', 'UPI')),
    CONSTRAINT chk_payments_amount CHECK (amount >= 0.00)
);

CREATE INDEX idx_payments_patient_paid_at
    ON payments (patient_id, paid_at DESC, id DESC);
